[[auto]]
keywordFull=["米哈游十连"]
content="#{DRAW-米哈游十连}"

[[auto]]
keywordFull=["原神十连"]
content="#{DRAW-原神十连}"

[[auto]]
keywordFull=["崩铁十连"]
content="#{DRAW-崩铁十连}"


[[auto]]
keywordFull=["崩三十连"]
content="#{DRAW-崩三十连}"

[[auto]]
keywordFull=["摸鱼鱼"]
content="#{PICTURE-https://api.vvhan.com/api/moyu}"

[[auto]]
keywordFull=["今日早报"]
content="#{PICTURE-https://api.03c3.cn/zb/}"
