[[define]]
name='''替换'''
content='''
function textUnescapeSpecialChars(str) {  
    // 使用正则表达式和replace方法的回调函数来替换转义字符  
    return str.replace(/\\(.|\[|\]|:|,|\\|n)/g, function(match) {  
        switch (match) {  
            case '\\[': return '[';  
            case '\\]': return ']';  
            case '\\:': return ':';  
            case '\\,': return ',';  
            case '\\\\': return '\\';  
            case '\\n': return '\n';  
            default: return match[1]; // 对于其他转义字符，返回其原始形式  
        }  
    });  
}
textUnescapeSpecialChars(v1);
'''

[[auto]]
keywordRegexp='''^&([\s\S]*)'''
program="""
【判断 【发送者QQ】,1953307848,【块】,
【赋值变量 test,【执行脚本 【常量 替换】,【正则匹配到的】】】【执行变量 test】#{MULT}&运行已完成。】
"""

[[auto]]
keywordRegexp='''^%%%%([\s\S]*)'''
program="""
【赋值变量 test,【执行脚本 【常量 替换】,【正则匹配到的】】】【执行变量 test】#{MULT}&运行已完成。
"""

[[auto]]
keywordRegexp='''^#&([\s\S]*)'''
program="""
【判断 【发送者QQ】,1953307848,【块】,
【赋值变量 test,【正则匹配到的】】【执行变量 test】
#{MULT}&运行已完成。】
"""

[[auto]]
keywordRegexp='''^%#%%%%([\s\S]*)'''
program="""
【赋值变量 test,【正则匹配到的】】【执行变量 test】
#{MULT}&运行已完成。
"""

[[auto]]
keywordRegexp="^js&([\\s\\S]*)"
0program="""
【判断 【发送者QQ】,1953307848,【块】,
【执行脚本 【执行脚本 【常量 替换】,【正则匹配到的】】】
#{MULT}js&运行已完成。】
"""
