[[auto]]
keywordFull=["早安"]
content="早安，新的一天也要元气满满哦(～￣▽￣)～"

[[auto]]
keywordFull=["晚安"]
program="""
【随取 
    屑#{AT-YOU}，你该不会说了晚安之后背着我偷偷继续玩手机吧(′。＿。｀),
    晚安，祝你做个好梦,
    晚安晚安，记得梦我
    】
"""

[[auto]]
keywordFull=["阿和"]
content="阿和我的！"

[[auto]]
keywordFull=["阿绫"]
content="阿绫我的！"

[[auto]]
keywordFull=["哭辽","哭"]
content="{AT-YOU}不哭，来抱抱＜（＾－＾）＞"

[[auto]]
keywordFull=["冒泡"]
program="""
【随取 
    戳破~,
    #戳
    】
"""

[[auto]]
keywordFull=["哈哈哈","hhc"]
program="""
【随取 
    在笑什么？能和天依说说吗XD,
    我看你好像很开心的样子，是遇到什么好事了吗
    】
"""

[[auto]]
keywordFull=["午安"]
content="午安，今天中午吃什么呢XD"

[[auto]]
keywordFull=["天依我爱你"]
program="""
【随取 
    我也爱你~,
    爱你哟~,
    =v=
    】
"""

[[auto]]
keywordFull=["捏天依"]
program="""
【随取 
    去去去，把手拿开,
    ？不许捏＞︿＜,
    哼！
    】
"""

[[auto]]
keywordFull=["夸天依"]
program="""
【随取 
    谢谢，嘿嘿嘿~,
    其实，也没有那么好啦（///V///）
    】
"""

[[auto]]
keywordFull=["天依"]
program="""
【随取 
    在！,
    <info:name>有什么事吗？,
    我听见有人叫我名字
    】
"""

[[auto]]
keywordFull=["天依唱首歌"]
program="""
【随取 
    我等春风吹来，雪也融化尘埃，人生再也没遗憾~,
    我的梦白如花，你的梦如晚霞，想关上城市灯光专心闻你发香~BV1Vp411d7iy,
    紧握 彼此间的 子午线，相隔那么遥远 还坚持 不停歇，空虚 却想抵过那岁月，那荒漠寂寥无边 也流连~BV1vs411y79q,
    是记得  相遇在一支歌，听你讲黎明时的世末歌者  勿忘草遗落BV1xx411H7SG,
    温柔的海浪声 一阵又一阵，宁静崖边小镇 亮起了街灯，菠萝与芒橙 椰子树与柠檬，海风的轻吻 清凉而又深沉~BV1us411v74g,
    灯火光影 被点亮 的街区，谁的心灵 被深藏 的过去，残存的记忆 被诉说 的言语，只剩下满天 繁星~BV1ft41157x1,
    你应该忘记了吧，天气晴朗，心里却潮湿的盛夏~而我还记得你那天写的歌，和对我说的话~BV1Tp4y1S7cu,
    如果比起 九十岁死去荣光缠裹，却无法在 此后被谁深情铭刻，我宁愿折三折 轰轰烈烈趟过，也偏要将错就错！BV12s411T7EY,
    有很多朋友是什么滋味？被人挂牵又会是什么滋味？所谓的合群  我好像做不对~BV1KZ4y157xQ,
    是流传千古 毋用谁来讲述，华夏的古谱 雕于魂刻于骨，炎黄铸血肉 时光琢发肤，以此躯延续千年之烛~BV1fJ411t7PK,
    写几曲彷徨，添几字迷茫，究竟有多少心事要我来唱~唱淡了月光，唱断了愁肠，远方姑娘却不在你身旁BV17t411y7Xw,
    蔷薇花安静绽放，熏香冰冷的水泥墙，闪耀着生命，温暖的光芒~BV1hW411B7so
    】
"""

[[auto]]
keywordFull=["吃天依","恰天依"]
program="""
【随取 
    我 不 能 吃 啦 ！！！,
    啊？你说什么？我没听见？你再说一次试试？,
    嗯？虽然我没听见你刚刚说的，但我父亲山新是很优秀的声优你要不要去做她粉丝
    】
"""

[[auto]]
keywordFull=["打天依","揍天依","锤天依"]
program="""
【随取 
    master！这里有变态欺负我！！！,
    阿绫！这里有变态欺负我！！！,
    阿和！这里有变态欺负我！！！,
    哦豁？你真以为我打不过你是吗？,
    你知道为什么我每顿吃那么多身材还不胖吗？你马上就会知道了
    】
"""

[[auto]]
keywordFull=["天依真棒"]
program="""
【随取 
    谢谢，嘿嘿嘿~,
    其实，也没有那么好啦（///V///）
    】
"""

