[[auto]]
keywordFull=["米哈游十连"]
content="#{DRAW-米哈游十连}"

[[auto]]
keywordFull=["原神十连"]
content="#{DRAW-原神十连}"

[[auto]]
keywordFull=["崩铁十连"]
content="#{DRAW-崩铁十连}"


[[auto]]
keywordFull=["崩三十连"]
content="#{DRAW-崩三十连}"

[[auto]]
keywordFull=["摸鱼鱼"]
content="#{PICTURE-https://api.vvhan.com/api/moyu}"

[[auto]]
keywordFull=["今日早报"]
content="#{PICTURE-https://api.03c3.cn/zb/}"


[[auto]]
keywordFull=["赵赵COC卡","赵怡然COC卡"]
content="赵赵的七版COC人物作成:\n力量45 体质15 体型45  \n敏捷15 外貌90 智力90  \n意志50 教育80 幸运40  \nDB-2 HP6 总和【430/470】"

[[auto]]
keywordFull=["算一卦"]
content="#{DRAW-算卦}"